# Generated by Django 3.1.7 on 2021-03-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_remove_signup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itemName',
            field=models.CharField(default='Food', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='phoneNum',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
