# Generated by Django 3.1.7 on 2021-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210319_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itemImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
