# Generated by Django 3.1.7 on 2021-03-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_items_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemImage',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
    ]
