# Generated by Django 3.1.7 on 2021-03-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20210320_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='itemImage',
            new_name='image',
        ),
    ]
