# Generated by Django 3.1.7 on 2021-03-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20210320_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
