# Generated by Django 3.1.7 on 2021-03-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20210331_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='items_list',
            field=models.CharField(max_length=5000),
        ),
    ]
