# Generated by Django 3.1.7 on 2021-03-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20210331_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='phoneNum',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
