# Generated by Django 3.1.7 on 2021-03-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20210331_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
