# Generated by Django 3.1.7 on 2021-03-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='string_id',
            field=models.CharField(default='-1', max_length=100),
        ),
    ]
